const fs = require('fs')
const path = require('path')

const CONFIG_PATH = path.join(__dirname, '../../config/ingestion_config.json')
const DELTA_LOG_PATH = path.join(__dirname, '../../logs/delta_log.jsonl')
const NODES_PATH = path.join(__dirname, '../../graph/nodes.json')

require('dotenv').config()
const Anthropic = require('@anthropic-ai/sdk')
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

function getLastIngestionTimestamp() {
  try {
    const lines = fs.readFileSync(DELTA_LOG_PATH, 'utf8').split('\n').filter(Boolean)
    const checkpoints = lines
      .map(l => { try { return JSON.parse(l) } catch (_) { return null } })
      .filter(e => e && e.event_type === 'SYNC_CHECKPOINT')
    if (checkpoints.length === 0) return 'Never'
    return checkpoints[checkpoints.length - 1].timestamp
  } catch (_) {
    return 'Unknown'
  }
}

function getFilesInKnowledgeBase() {
  try {
    const nodes = JSON.parse(fs.readFileSync(NODES_PATH, 'utf8'))
    return nodes.filter(n => n.type === 'FILE_SOURCE' && n.data.ingestion_status === 'complete').length
  } catch (_) {
    return 0
  }
}

function getAudioCostForSources(sources) {
  return sources
    .filter(s => s.transcription_cost_usd)
    .reduce((sum, s) => sum + s.transcription_cost_usd, 0)
}

function formatSourceCitation(source) {
  const author = source.author || '[author unknown]'
  const modified = source.last_modified ? new Date(source.last_modified).toISOString().split('T')[0] : 'unknown date'
  return `• ${source.filename} | ${source.file_type} | ${author} | ${modified} | ${source.path}`
}

function formatExternalCitation(result) {
  if (!result || !result.result) return null
  const retrieved = result.retrieved_at ? new Date(result.retrieved_at).toISOString().split('T')[0] : 'unknown'
  const sourceName = result.source === 'genspark' ? 'Genspark Research' : 'Claude Web Search'
  return `• ${sourceName} | retrieved: ${retrieved}`
}

function buildTransparencyFooter(sources, config) {
  const rootFolder = config.ingestion_path || 'Not configured'
  const filesInKb = getFilesInKnowledgeBase()
  const lastIngestion = getLastIngestionTimestamp()
  const filesAccessed = sources.length
  const audioCost = getAudioCostForSources(sources)

  let footer = `─── Knowledge Base Transparency ───────────────────────────────────\n`
  footer += `Root folder: ${rootFolder}\n`
  footer += `Files in knowledge base: ${filesInKb}\n`
  footer += `Files accessed this response: ${filesAccessed}\n`
  footer += `Last ingestion: ${lastIngestion}`

  if (audioCost > 0) {
    footer += `\nAudio transcription cost this session: $${audioCost.toFixed(4)}`
  }

  return footer
}

async function generateAnswer(query, internalResults) {
  const context = internalResults?.results?.slice(0, 10)
    .map(n => JSON.stringify(n.data, null, 2))
    .join('\n\n') || 'No internal knowledge found.'

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 2000,
    messages: [{
      role: 'user',
      content: `Answer the following question using ONLY the context below. Be specific, cite facts from the context, and do not reproduce verbatim content.\n\nQuestion: ${query}\n\nContext:\n${context}`,
    }],
  })

  return response.content[0].text
}

async function synthesise(routerResult) {
  const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'))

  if (routerResult.refused) {
    return routerResult.refusal_message
  }

  const answer = await generateAnswer(routerResult.query, routerResult.internal_results)

  const sources = routerResult.sources || []
  const internalCitations = sources.map(formatSourceCitation).join('\n')

  let response = answer + '\n\n'

  if (sources.length > 0) {
    response += `─── Internal Sources ──────────────────────────────────────────────\n`
    response += internalCitations + '\n\n'
  }

  const externalFormatted = formatExternalCitation(routerResult.external_results)
  if (externalFormatted) {
    response += `─── External Research (via Genspark) ──────────────────────────────\n`
    response += externalFormatted + '\n\n'
  }

  response += buildTransparencyFooter(sources, config)

  return response
}

function buildArtefactFooter(sourcesCount, externalCount, config) {
  const rootFolder = config.ingestion_path || 'Not configured'
  const lastIngestion = getLastIngestionTimestamp()
  return `---\nArtefact generated by Atlas | ${new Date().toISOString()}\nSources: ${sourcesCount} internal files | ${externalCount} external sources\nRoot folder: ${rootFolder}\nLast ingestion: ${lastIngestion}`
}

module.exports = { synthesise, buildArtefactFooter, getLastIngestionTimestamp, getFilesInKnowledgeBase }
